export interface CorporateFunctionalContact {
  id: string;
  functionName: string;
  email: string;
  category: "Executive Leadership" | "Corporate Functional" | "Commercial & Supply Chain";
  officerName?: string;
  description?: string;
}

export interface IndustryDivisionContact {
  id: string;
  divisionName: string;
  email: string;
  sector: "High-Tech & Aerospace" | "Heavy Industry & Resources" | "Agri & Commodities" | "Healthcare & Life Sciences" | "Consumer & Lifestyle" | "Energy & Infrastructure";
}

export interface RegionalHQContact {
  id: string;
  company: string;
  headquarters: string;
  regionalContact: string;
  email: string;
  continent: "Europe" | "Americas" | "Africa" | "Middle East" | "Asia" | "Oceania";
  flag: string;
}

export const CORPORATE_FUNCTIONAL_CONTACTS: CorporateFunctionalContact[] = [
  {
    id: "func-01",
    functionName: "Corporate Headquarters",
    email: "admin@takniser.com",
    category: "Corporate Functional",
    description: "Central Administration, Global Executive Secretariat & Group Management",
  },
  {
    id: "func-02",
    functionName: "International Business",
    email: "ib@takniser.com",
    category: "Commercial & Supply Chain",
    description: "Cross-border partnerships, multinational joint ventures & market entry",
  },
  {
    id: "func-03",
    functionName: "Global Sales",
    email: "sales@takniser.com",
    category: "Commercial & Supply Chain",
    description: "Worldwide commercial contracts, tenders & client relationship management",
  },
  {
    id: "func-04",
    functionName: "Global Logistics & Supply Chain",
    email: "logistics@takniser.com",
    category: "Commercial & Supply Chain",
    description: "Multimodal freight forwarding, bonded warehousing & corridor management",
  },
  {
    id: "func-05",
    functionName: "Global Procurement & Sourcing",
    email: "procurement@takniser.com",
    category: "Commercial & Supply Chain",
    description: "Vendor qualification, industrial equipment sourcing & supplier management",
  },
  {
    id: "func-06",
    functionName: "Finance & Treasury",
    email: "finance@takniser.com",
    category: "Corporate Functional",
    description: "Trade finance, capital management, group accounting & treasury operations",
  },
  {
    id: "func-07",
    functionName: "Legal & Compliance",
    email: "legal@takniser.com",
    category: "Corporate Functional",
    description: "Corporate governance, international trade compliance & contract law",
  },
  {
    id: "func-08",
    functionName: "Human Resources",
    email: "hr@takniser.com",
    category: "Corporate Functional",
    description: "Global talent acquisition, executive placement & workforce development",
  },
  {
    id: "func-09",
    functionName: "Corporate Communications",
    email: "media@takniser.com",
    category: "Corporate Functional",
    description: "Media inquiries, corporate public relations & institutional relations",
  },
  {
    id: "func-10",
    functionName: "Investor Relations",
    email: "investors@takniser.com",
    category: "Corporate Functional",
    description: "Shareholder services, financial reports & investment advisory",
  },
  {
    id: "func-11",
    functionName: "Chief Executive Officer",
    email: "heinrich.schutz@takniser.com",
    category: "Executive Leadership",
    officerName: "Heinrich Schütz",
    description: "Office of the Chief Executive Officer — TAKNISER Group",
  },
  {
    id: "func-12",
    functionName: "Chief People Officer",
    email: "louise.sendorf@takniser.com",
    category: "Executive Leadership",
    officerName: "Louise Sendorf",
    description: "Global People, Culture & Strategic Talent Directorate",
  },
  {
    id: "func-13",
    functionName: "Chief Financial Officer",
    email: "steffen.klein@takniser.com",
    category: "Executive Leadership",
    officerName: "Steffen Klein",
    description: "Global Financial Strategy, Treasury & Capital Oversight",
  },
];

export const INDUSTRY_DIVISION_CONTACTS: IndustryDivisionContact[] = [
  {
    id: "ind-01",
    divisionName: "Space Economy",
    email: "spaceeconmy@takniser.com",
    sector: "High-Tech & Aerospace",
  },
  {
    id: "ind-02",
    divisionName: "Aerospace",
    email: "aerospace@takniser.com",
    sector: "High-Tech & Aerospace",
  },
  {
    id: "ind-03",
    divisionName: "Defence Systems",
    email: "defence@takniser.com",
    sector: "High-Tech & Aerospace",
  },
  {
    id: "ind-04",
    divisionName: "Mining & Minerals",
    email: "mining@takniser.com",
    sector: "Heavy Industry & Resources",
  },
  {
    id: "ind-05",
    divisionName: "Infrastructure",
    email: "infrastructure@takniser.com",
    sector: "Energy & Infrastructure",
  },
  {
    id: "ind-06",
    divisionName: "Marine & Offshore",
    email: "marine@takniser.com",
    sector: "Heavy Industry & Resources",
  },
  {
    id: "ind-07",
    divisionName: "AgTech Machinery",
    email: "agtech@takniser.com",
    sector: "Agri & Commodities",
  },
  {
    id: "ind-08",
    divisionName: "Agriculture",
    email: "agriculture@takniser.com",
    sector: "Agri & Commodities",
  },
  {
    id: "ind-09",
    divisionName: "Food & Agri Commodities",
    email: "agri@takniser.com",
    sector: "Agri & Commodities",
  },
  {
    id: "ind-10",
    divisionName: "Healthcare & Life Sciences",
    email: "lifecare@takniser.com",
    sector: "Healthcare & Life Sciences",
  },
  {
    id: "ind-11",
    divisionName: "Pharma",
    email: "Pharma@takniser.com",
    sector: "Healthcare & Life Sciences",
  },
  {
    id: "ind-12",
    divisionName: "Consumer Electronics",
    email: "electronics@takniser.com",
    sector: "Consumer & Lifestyle",
  },
  {
    id: "ind-13",
    divisionName: "Home Appliances",
    email: "appliances@takniser.com",
    sector: "Consumer & Lifestyle",
  },
  {
    id: "ind-14",
    divisionName: "Textiles & Lifestyle",
    email: "lifestyle@takniser.com",
    sector: "Consumer & Lifestyle",
  },
  {
    id: "ind-15",
    divisionName: "Retail & Distribution",
    email: "retail@takniser.com",
    sector: "Consumer & Lifestyle",
  },
  {
    id: "ind-16",
    divisionName: "Global Trading",
    email: "trading@takniser.com",
    sector: "Heavy Industry & Resources",
  },
  {
    id: "ind-17",
    divisionName: "Electrical Systems",
    email: "electrical@takniser.com",
    sector: "Energy & Infrastructure",
  },
  {
    id: "ind-18",
    divisionName: "Lighting Solutions",
    email: "lighting@takniser.com",
    sector: "Energy & Infrastructure",
  },
  {
    id: "ind-19",
    divisionName: "Wire & Cable",
    email: "wirecable@takniser.com",
    sector: "Energy & Infrastructure",
  },
  {
    id: "ind-20",
    divisionName: "Power & Energy",
    email: "energy@takniser.com",
    sector: "Energy & Infrastructure",
  },
  {
    id: "ind-21",
    divisionName: "Renewable Energy",
    email: "renewable@takniser.com",
    sector: "Energy & Infrastructure",
  },
  {
    id: "ind-22",
    divisionName: "Industrial Automation",
    email: "automation@takniser.com",
    sector: "High-Tech & Aerospace",
  },
  {
    id: "ind-23",
    divisionName: "Robotics",
    email: "robotics@takniser.com",
    sector: "High-Tech & Aerospace",
  },
];

export const REGIONAL_HQ_CONTACTS: RegionalHQContact[] = [
  {
    id: "rhq-01",
    company: "TAKNISER GmbH",
    headquarters: "Dillenburg, Germany",
    regionalContact: "Central Europe HQ",
    email: "admin@takniser.com",
    continent: "Europe",
    flag: "🇩🇪",
  },
  {
    id: "rhq-02",
    company: "TAKNISER AB",
    headquarters: "Stockholm, Sweden",
    regionalContact: "Scandinavia RHQ",
    email: "info.sweden@takniser.com",
    continent: "Europe",
    flag: "🇸🇪",
  },
  {
    id: "rhq-03",
    company: "TAKNISER Meyer Baltique OÜ",
    headquarters: "Tallinn, Estonia",
    regionalContact: "Baltic RHQ",
    email: "info.estonia@takniser.com",
    continent: "Europe",
    flag: "🇪🇪",
  },
  {
    id: "rhq-04",
    company: "TAKNISER GmbH",
    headquarters: "Dillenburg, Germany",
    regionalContact: "Central Europe RHQ",
    email: "admin@takniser.com",
    continent: "Europe",
    flag: "🇩🇪",
  },
  {
    id: "rhq-05",
    company: "TAKNISER Bernard Laurent SARL",
    headquarters: "Paris, France",
    regionalContact: "France RHQ",
    email: "info.france@takniser.com",
    continent: "Europe",
    flag: "🇫🇷",
  },
  {
    id: "rhq-06",
    company: "TAKNISER Vries Benelux B.V.",
    headquarters: "Rotterdam, Netherlands",
    regionalContact: "Benelux RHQ",
    email: "info.netherlands@takniser.com",
    continent: "Europe",
    flag: "🇳🇱",
  },
  {
    id: "rhq-07",
    company: "TAKNISER Veneto Industriale S.R.L.",
    headquarters: "Milan, Italy",
    regionalContact: "Southern Europe RHQ",
    email: "info.italia@takniser.com",
    continent: "Europe",
    flag: "🇮🇹",
  },
  {
    id: "rhq-08",
    company: "TAKNISER Velasco Iberia S.L.",
    headquarters: "Madrid, Spain",
    regionalContact: "Iberia RHQ",
    email: "info.spain@takniser.com",
    continent: "Europe",
    flag: "🇪🇸",
  },
  {
    id: "rhq-09",
    company: "TAKNISER Roths UK Ltd",
    headquarters: "London, UK",
    regionalContact: "UK & Ireland RHQ",
    email: "info.uk@takniser.com",
    continent: "Europe",
    flag: "🇬🇧",
  },
  {
    id: "rhq-10",
    company: "TAKNISER Sterling Americana LLC",
    headquarters: "Texas, USA",
    regionalContact: "North America RHQ",
    email: "info.usa@takniser.com",
    continent: "Americas",
    flag: "🇺🇸",
  },
  {
    id: "rhq-11",
    company: "TAKNISER Ortega Panamá S.A.",
    headquarters: "Panama City",
    regionalContact: "Central America RHQ",
    email: "info.panama@takniser.com",
    continent: "Americas",
    flag: "🇵🇦",
  },
  {
    id: "rhq-12",
    company: "TAKNISER Santos Amazonia Ltda.",
    headquarters: "São Paulo",
    regionalContact: "South America RHQ",
    email: "info.brazil@takniser.com",
    continent: "Americas",
    flag: "🇧🇷",
  },
  {
    id: "rhq-13",
    company: "TAKNISER Pinault AOF Ltd",
    headquarters: "Accra",
    regionalContact: "West Africa RHQ",
    email: "info.westafrica@takniser.com",
    continent: "Africa",
    flag: "🇬🇭",
  },
  {
    id: "rhq-14",
    company: "TAKNISER Menard Kenya Ltd",
    headquarters: "Nairobi",
    regionalContact: "East Africa RHQ",
    email: "info.kenya@takniser.com",
    continent: "Africa",
    flag: "🇰🇪",
  },
  {
    id: "rhq-15",
    company: "TAKNISER Ratcliff Savanna Pty Ltd",
    headquarters: "Johannesburg",
    regionalContact: "Southern Africa RHQ",
    email: "info.southafrica@takniser.com",
    continent: "Africa",
    flag: "🇿🇦",
  },
  {
    id: "rhq-16",
    company: "TAKNISER GmbH Trading LLC",
    headquarters: "Dubai",
    regionalContact: "Middle East RHQ",
    email: "info.uae@takniser.com",
    continent: "Middle East",
    flag: "🇦🇪",
  },
  {
    id: "rhq-17",
    company: "TAKNISER SARL E&ET FZCO",
    headquarters: "Jafza-UAE",
    regionalContact: "UAE",
    email: "info.jafza@takniser.com",
    continent: "Middle East",
    flag: "🇦🇪",
  },
  {
    id: "rhq-18",
    company: "TAKNISER Hoffmann Arabia LLC",
    headquarters: "Dammam",
    regionalContact: "Saudi RHQ",
    email: "info.saudiarabia@takniser.com",
    continent: "Middle East",
    flag: "🇸🇦",
  },
  {
    id: "rhq-19",
    company: "TAKNISER AB India Pvt Ltd",
    headquarters: "India",
    regionalContact: "South Asia RHQ",
    email: "info.india@takniser.com",
    continent: "Asia",
    flag: "🇮🇳",
  },
  {
    id: "rhq-20",
    company: "TAKNISER Merlion Singapore Pte Ltd",
    headquarters: "Singapore",
    regionalContact: "ASEAN RHQ",
    email: "info.singapore@takniser.com",
    continent: "Asia",
    flag: "🇸🇬",
  },
  {
    id: "rhq-21",
    company: "TAKNISER Shuliang China Co., Ltd.",
    headquarters: "Guangzhou",
    regionalContact: "China RHQ",
    email: "info.china@takniser.com",
    continent: "Asia",
    flag: "🇨🇳",
  },
  {
    id: "rhq-22",
    company: "TAKNISER Shānshān HK Ltd",
    headquarters: "Hong Kong",
    regionalContact: "North Asia RHQ",
    email: "info.hongkong@takniser.com",
    continent: "Asia",
    flag: "🇭🇰",
  },
  {
    id: "rhq-23",
    company: "TAKNISER Takemitsu Japan K.K.",
    headquarters: "Tokyo",
    regionalContact: "Japan RHQ",
    email: "info.japan@takniser.com",
    continent: "Asia",
    flag: "🇯🇵",
  },
  {
    id: "rhq-24",
    company: "TAKNISER Sahenk Turk A.Ş.",
    headquarters: "Istanbul",
    regionalContact: "Türkiye RHQ",
    email: "info.turkiye@takniser.com",
    continent: "Asia",
    flag: "🇹🇷",
  },
  {
    id: "rhq-25",
    company: "TAKNISER Pallmer Pacific Pty Ltd",
    headquarters: "Melbourne",
    regionalContact: "Oceania RHQ",
    email: "info.australia@takniser.com",
    continent: "Oceania",
    flag: "🇦🇺",
  },
];
